'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const id='1'.repeat(24);
function setup(){let definition;const calls={cloud:0,preview:[],pause:0,copy:0};global.wx={cloud:{callFunction:async()=>{calls.cloud++;return{};}},previewImage:o=>calls.preview.push(o),createVideoContext:()=>({pause:()=>calls.pause++}),setClipboardData:()=>calls.copy++};global.Page=d=>definition=d;const p=require.resolve('../miniprogram/pages/detail/detail');delete require.cache[p];require(p);delete global.Page;
 return{page:{...definition,data:structuredClone(definition.data),setData(patch){Object.assign(this.data,patch);}},calls};}
function content(){return{note:{noteId:id,title:'蒸蛋',author:'作者',type:'video',publishedAt:'2026-09-12T01:00:00Z'},content:{status:'available',desc:'鸡蛋2个，加水蒸熟',bodyComplete:true,images:['https://sns-i11.rednotecdn.com/1.jpg','https://sns-i11.rednotecdn.com/2.jpg'],imageCount:2,imagesComplete:true,videoUrl:'https://sns-v11.rednotecdn.com/1.mp4',capturedAt:'2026-09-12T01:02:00Z'}};}
test('invalid entry identifiers cannot invoke backend or expose stale content',()=>{const x=setup();x.page.onLoad({noteId:'../secret'});assert.equal(x.calls.cloud,0);assert.equal(x.page.data.loading,false);assert.equal(x.page.data.note,null);});
test('detail displays stored text and video, with media errors isolated from text and no clipboard writes',async()=>{const x=setup();x.page._noteId=id;x.page._api=async action=>{assert.equal(action,'getContent');return content();};await x.page.loadContent();assert.equal(x.page.data.content.desc,'鸡蛋2个，加水蒸熟');assert.equal(x.page.data.loading,false);assert.equal(x.page.data.canOpenOriginal,false);x.page.onVideoError();assert.equal(x.page.data.videoFailed,true);assert.equal(x.page.data.content.desc,'鸡蛋2个，加水蒸熟');x.page.onHide();assert.equal(x.calls.pause,1);assert.equal(x.calls.copy,0);});
test('image preview excludes failed images and never accepts an arbitrary event URL',async()=>{const x=setup();x.page._noteId=id;x.page._api=async()=>content();await x.page.loadContent();x.page.onImageError({currentTarget:{dataset:{index:'0'}}});x.page.onPreviewImage({currentTarget:{dataset:{index:'0'}}});assert.equal(x.calls.preview.length,0);x.page.onPreviewImage({currentTarget:{dataset:{index:'1'}}});assert.deepEqual(x.calls.preview[0].urls,['https://sns-i11.rednotecdn.com/2.jpg']);});
test('late replies cannot replace a newer result or redisplay content after an authorization refusal',async()=>{const x=setup();x.page._noteId=id;let first;const delayed=new Promise(r=>first=r);x.page._api=()=>delayed;const pending=x.page.loadContent();x.page._api=async()=>{throw Error('这个账号已停用');};await x.page.loadContent();first(content());await pending;assert.equal(x.page.data.note,null);assert.equal(x.page.data.content,null);assert.equal(x.page.data.message,'这个账号已停用');});
test('network failure never claims that cleared content was preserved',async()=>{const x=setup();x.page._noteId=id;x.page._api=async()=>{throw Object.assign(Error('连接失败，原有内容已保留。'),{code:'NETWORK_ERROR'});};await x.page.loadContent();assert.equal(x.page.data.note,null);assert.equal(x.page.data.message,'连接失败，请重试。');});
test('portrait and landscape video layouts use bounded aspect ratios',()=>{const x=setup();x.page.onVideoMetadata({detail:{width:1080,height:1920}});assert.equal(x.page.data.videoHeight,1000);x.page.onVideoMetadata({detail:{width:1920,height:1080}});assert.equal(x.page.data.videoHeight,386);x.page.onVideoMetadata({detail:{width:0,height:100}});assert.equal(x.page.data.videoHeight,386);});
test('author button uses loaded identity, prevents duplicate launches, and clears after access refusal',async()=>{
 const x=setup(),authorId='2'.repeat(24);x.page._noteId=id;x.page._api=async()=>({...content(),note:{...content().note,authorId,authorNavigation:{authorId,token:'shared-token',source:'app_share'}}});
 await x.page.loadContent();assert.equal(x.page.data.canOpenAuthor,true);let callback,count=0;global.wx.navigateToMiniProgram=o=>{count++;callback=o;};global.wx.showToast=()=>assert.fail('cancellation is not an error');
 const pending=x.page.onOpenAuthor();await x.page.onOpenAuthor();assert.equal(count,1);assert.ok(callback.path.includes('author_id='+authorId));callback.fail({errMsg:'cancel'});await pending;assert.equal(x.page.data.openingAuthor,false);
 x.page._api=async()=>{throw Error('停用');};await x.page.loadContent();assert.equal(x.page.data.canOpenAuthor,false);await x.page.onOpenAuthor();assert.equal(count,1);assert.equal(x.calls.copy,0);
});
